/**
 * Integration Catalog — Full Vercel Marketplace + Native + External integrations
 * Each integration maps to a category, provider key, env var pattern, and available tools.
 */

export type IntegrationCategory =
  | "ai"
  | "storage"
  | "observability"
  | "analytics"
  | "authentication"
  | "cms"
  | "commerce"
  | "messaging"
  | "monitoring"
  | "searching"
  | "security"
  | "web_automation"
  | "support_agent"
  | "code_review"
  | "testing"
  | "devtools"
  | "logging"
  | "video"
  | "payments"
  | "government"

export type IntegrationTier = "native" | "agent" | "external"

export interface IntegrationEntry {
  /** Unique provider key */
  id: string
  /** Display name */
  name: string
  /** One-line description */
  description: string
  /** Category for filtering */
  category: IntegrationCategory
  /** native = first-party Vercel, agent = AI agent service, external = third-party */
  tier: IntegrationTier
  /** Environment variable names this integration needs */
  envKeys: string[]
  /** Whether this integration uses OAuth flow */
  oauth: boolean
  /** URL to the provider's docs/dashboard */
  docsUrl: string
  /** Whether this integration is featured */
  featured: boolean
  /** Whether this is enabled/available (some are coming soon) */
  available: boolean
  /** Tools this integration provides to agents */
  agentTools: string[]
}

// ─── Full Integration Catalog ─────────────────────────────────────────────────

export const INTEGRATION_CATALOG: IntegrationEntry[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // NATIVE INTEGRATIONS (Vercel first-party)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- Storage ---
  {
    id: "supabase",
    name: "Supabase",
    description: "Open-source Postgres development platform that scales to millions.",
    category: "storage",
    tier: "native",
    envKeys: ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY"],
    oauth: false,
    docsUrl: "https://supabase.com/docs",
    featured: true,
    available: true,
    agentTools: ["db:query_data", "db:read_schema", "db:write_data", "db:run_migration"],
  },
  {
    id: "neon",
    name: "Neon",
    description: "Postgres serverless platform designed to build reliable and scalable apps.",
    category: "storage",
    tier: "native",
    envKeys: ["NEON_DATABASE_URL"],
    oauth: false,
    docsUrl: "https://neon.tech/docs",
    featured: true,
    available: true,
    agentTools: ["db:query", "db:branch"],
  },
  {
    id: "upstash",
    name: "Upstash",
    description: "Serverless DB (Redis, Vector, Queue, Search).",
    category: "storage",
    tier: "native",
    envKeys: ["UPSTASH_REDIS_REST_URL", "UPSTASH_REDIS_REST_TOKEN"],
    oauth: false,
    docsUrl: "https://upstash.com/docs",
    featured: true,
    available: true,
    agentTools: ["cache:get", "cache:set", "cache:del", "vector:upsert", "vector:query", "queue:publish"],
  },
  {
    id: "redis",
    name: "Redis",
    description: "Serverless Redis.",
    category: "storage",
    tier: "native",
    envKeys: ["REDIS_URL"],
    oauth: false,
    docsUrl: "https://redis.io/docs",
    featured: false,
    available: true,
    agentTools: ["cache:get", "cache:set", "cache:del"],
  },
  {
    id: "mongodb",
    name: "MongoDB Atlas",
    description: "Document model, distributed architecture, robust search and vector capabilities.",
    category: "storage",
    tier: "native",
    envKeys: ["MONGODB_URL", "MONGODB_DATA_API_URL", "MONGODB_DATA_API_KEY"],
    oauth: false,
    docsUrl: "https://www.mongodb.com/docs/atlas",
    featured: false,
    available: true,
    agentTools: ["doc:find", "doc:insert", "doc:update", "doc:aggregate", "vector:search"],
  },
  {
    id: "aws",
    name: "AWS",
    description: "Serverless, reliable, secure PostgreSQL and NoSQL databases.",
    category: "storage",
    tier: "native",
    envKeys: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"],
    oauth: false,
    docsUrl: "https://aws.amazon.com/documentation",
    featured: false,
    available: true,
    agentTools: ["s3:list", "s3:get", "s3:put", "dynamodb:query"],
  },
  {
    id: "convex",
    name: "Convex",
    description: "Open-source backend platform that keeps your app in sync.",
    category: "storage",
    tier: "native",
    envKeys: ["CONVEX_URL", "CONVEX_DEPLOY_KEY"],
    oauth: false,
    docsUrl: "https://docs.convex.dev",
    featured: false,
    available: true,
    agentTools: ["convex:query", "convex:mutation"],
  },
  {
    id: "turso",
    name: "Turso Cloud",
    description: "SQLite for the age of AI.",
    category: "storage",
    tier: "native",
    envKeys: ["TURSO_DATABASE_URL", "TURSO_AUTH_TOKEN"],
    oauth: false,
    docsUrl: "https://docs.turso.tech",
    featured: false,
    available: true,
    agentTools: ["sql:query", "sql:execute"],
  },
  {
    id: "pinecone",
    name: "Pinecone",
    description: "Power your AI products with Pinecone vector database.",
    category: "storage",
    tier: "native",
    envKeys: ["PINECONE_API_KEY", "PINECONE_INDEX"],
    oauth: false,
    docsUrl: "https://docs.pinecone.io",
    featured: false,
    available: true,
    agentTools: ["vector:upsert", "vector:query", "vector:delete"],
  },
  {
    id: "nile",
    name: "Nile",
    description: "PostgreSQL re-engineered for B2B apps.",
    category: "storage",
    tier: "native",
    envKeys: ["NILE_DATABASE_URL"],
    oauth: false,
    docsUrl: "https://nile.dev/docs",
    featured: false,
    available: true,
    agentTools: ["db:query", "db:tenant_isolate"],
  },
  {
    id: "motherduck",
    name: "MotherDuck",
    description: "The serverless backend for analytics.",
    category: "storage",
    tier: "native",
    envKeys: ["MOTHERDUCK_TOKEN"],
    oauth: false,
    docsUrl: "https://motherduck.com/docs",
    featured: false,
    available: true,
    agentTools: ["analytics:query"],
  },
  {
    id: "prisma",
    name: "Prisma",
    description: "Instant Serverless Postgres.",
    category: "storage",
    tier: "native",
    envKeys: ["DATABASE_URL"],
    oauth: false,
    docsUrl: "https://www.prisma.io/docs",
    featured: false,
    available: true,
    agentTools: ["db:query"],
  },
  {
    id: "mixedbread",
    name: "Mixedbread",
    description: "The Search API for your data. Add multimodal & multilingual search.",
    category: "searching",
    tier: "agent",
    envKeys: ["MIXEDBREAD_API_KEY"],
    oauth: false,
    docsUrl: "https://mixedbread.ai/docs",
    featured: false,
    available: true,
    agentTools: ["search:multimodal", "embed:text"],
  },

  // --- AI Providers ---
  {
    id: "openai",
    name: "OpenAI",
    description: "GPT-4.1, GPT-4o, and o-series reasoning models.",
    category: "ai",
    tier: "external",
    envKeys: ["OPENAI_API_KEY"],
    oauth: false,
    docsUrl: "https://platform.openai.com/docs",
    featured: true,
    available: true,
    agentTools: ["llm:generate", "llm:embed", "llm:vision"],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    description: "Claude 4.5 Opus, Sonnet, and Haiku models.",
    category: "ai",
    tier: "external",
    envKeys: ["ANTHROPIC_API_KEY"],
    oauth: false,
    docsUrl: "https://docs.anthropic.com",
    featured: true,
    available: true,
    agentTools: ["llm:generate", "llm:vision", "llm:tool_use"],
  },
  {
    id: "xai",
    name: "xAI",
    description: "Grok by xAI.",
    category: "ai",
    tier: "native",
    envKeys: ["XAI_API_KEY"],
    oauth: false,
    docsUrl: "https://docs.x.ai",
    featured: false,
    available: true,
    agentTools: ["llm:generate", "llm:realtime"],
  },
  {
    id: "groq",
    name: "Groq",
    description: "Fast inference for AI applications.",
    category: "ai",
    tier: "native",
    envKeys: ["GROQ_API_KEY"],
    oauth: false,
    docsUrl: "https://console.groq.com/docs",
    featured: false,
    available: true,
    agentTools: ["llm:generate_fast"],
  },
  {
    id: "fal",
    name: "fal",
    description: "Generative media platform for developers.",
    category: "ai",
    tier: "native",
    envKeys: ["FAL_KEY"],
    oauth: false,
    docsUrl: "https://fal.ai/docs",
    featured: false,
    available: true,
    agentTools: ["media:generate_image", "media:generate_video"],
  },
  {
    id: "deepinfra",
    name: "Deep Infra",
    description: "Deep Infra AI integration.",
    category: "ai",
    tier: "native",
    envKeys: ["DEEPINFRA_API_KEY"],
    oauth: false,
    docsUrl: "https://deepinfra.com/docs",
    featured: false,
    available: true,
    agentTools: ["llm:generate", "llm:embed"],
  },
  {
    id: "together",
    name: "Together AI",
    description: "The cloud platform for generative AI.",
    category: "ai",
    tier: "external",
    envKeys: ["TOGETHER_API_KEY"],
    oauth: false,
    docsUrl: "https://docs.together.ai",
    featured: false,
    available: true,
    agentTools: ["llm:generate", "llm:finetune"],
  },
  {
    id: "replicate",
    name: "Replicate",
    description: "Run AI with an API.",
    category: "ai",
    tier: "external",
    envKeys: ["REPLICATE_API_TOKEN"],
    oauth: false,
    docsUrl: "https://replicate.com/docs",
    featured: false,
    available: true,
    agentTools: ["llm:generate", "media:generate"],
  },
  {
    id: "perplexity",
    name: "Perplexity API",
    description: "Access Perplexity's cutting edge LLMs for search-augmented generation.",
    category: "ai",
    tier: "external",
    envKeys: ["PERPLEXITY_API_KEY"],
    oauth: false,
    docsUrl: "https://docs.perplexity.ai",
    featured: false,
    available: true,
    agentTools: ["search:web_llm"],
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "The most powerful AI text to speech API.",
    category: "ai",
    tier: "external",
    envKeys: ["ELEVENLABS_API_KEY"],
    oauth: false,
    docsUrl: "https://elevenlabs.io/docs",
    featured: false,
    available: true,
    agentTools: ["audio:tts", "audio:voice_clone"],
  },
  {
    id: "lmnt",
    name: "LMNT",
    description: "Fast text-to-speech & voice cloning.",
    category: "ai",
    tier: "external",
    envKeys: ["LMNT_API_KEY"],
    oauth: false,
    docsUrl: "https://docs.lmnt.com",
    featured: false,
    available: true,
    agentTools: ["audio:tts"],
  },
  {
    id: "google-ai",
    name: "Google AI",
    description: "Gemini models for multimodal AI.",
    category: "ai",
    tier: "external",
    envKeys: ["GOOGLE_API_KEY"],
    oauth: false,
    docsUrl: "https://ai.google.dev/docs",
    featured: false,
    available: true,
    agentTools: ["llm:generate", "llm:vision", "llm:embed"],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    description: "Open-weight and frontier AI models.",
    category: "ai",
    tier: "external",
    envKeys: ["MISTRAL_API_KEY"],
    oauth: false,
    docsUrl: "https://docs.mistral.ai",
    featured: false,
    available: true,
    agentTools: ["llm:generate", "llm:embed"],
  },

  // --- Observability & Monitoring ---
  {
    id: "sentry",
    name: "Sentry",
    description: "Unified error and performance monitoring.",
    category: "observability",
    tier: "native",
    envKeys: ["SENTRY_DSN", "SENTRY_AUTH_TOKEN", "SENTRY_ORG", "SENTRY_PROJECT"],
    oauth: false,
    docsUrl: "https://docs.sentry.io",
    featured: true,
    available: true,
    agentTools: ["observe:capture_error", "observe:capture_message"],
  },
  {
    id: "dash0",
    name: "Dash0",
    description: "Logs, Traces and Metrics — simplified.",
    category: "observability",
    tier: "native",
    envKeys: ["DASH0_AUTH_TOKEN"],
    oauth: false,
    docsUrl: "https://www.dash0.com/docs",
    featured: false,
    available: true,
    agentTools: ["observe:log", "observe:trace"],
  },
  {
    id: "datadog",
    name: "Datadog",
    description: "See it all in one place.",
    category: "observability",
    tier: "external",
    envKeys: ["DD_API_KEY", "DD_SITE"],
    oauth: false,
    docsUrl: "https://docs.datadoghq.com",
    featured: false,
    available: true,
    agentTools: ["observe:metric", "observe:log", "observe:trace"],
  },
  {
    id: "braintrust",
    name: "Braintrust",
    description: "AI evaluation, monitoring, and observability for your Vercel applications.",
    category: "observability",
    tier: "agent",
    envKeys: ["BRAINTRUST_API_KEY"],
    oauth: false,
    docsUrl: "https://www.braintrust.dev/docs",
    featured: false,
    available: true,
    agentTools: ["eval:log", "eval:score"],
  },
  {
    id: "checkly",
    name: "Checkly",
    description: "Test & monitor with Playwright. Reliability built for modern engineering teams.",
    category: "monitoring",
    tier: "native",
    envKeys: ["CHECKLY_API_KEY", "CHECKLY_ACCOUNT_ID"],
    oauth: false,
    docsUrl: "https://www.checklyhq.com/docs",
    featured: false,
    available: true,
    agentTools: ["monitor:health_check", "monitor:api_check"],
  },
  {
    id: "kubiks",
    name: "Kubiks",
    description: "Logs, Traces, Dashboards, Alerts, Automatic Pull Requests with fixes.",
    category: "observability",
    tier: "agent",
    envKeys: ["KUBIKS_API_KEY"],
    oauth: false,
    docsUrl: "https://kubiks.io/docs",
    featured: false,
    available: true,
    agentTools: ["observe:log", "observe:alert"],
  },
  {
    id: "rollbar",
    name: "Rollbar",
    description: "Real-time crash & error reporting, $0/mo.",
    category: "observability",
    tier: "native",
    envKeys: ["ROLLBAR_ACCESS_TOKEN"],
    oauth: false,
    docsUrl: "https://docs.rollbar.com",
    featured: false,
    available: true,
    agentTools: ["observe:capture_error"],
  },
  {
    id: "newrelic",
    name: "New Relic",
    description: "Explore and analyze logs.",
    category: "observability",
    tier: "external",
    envKeys: ["NEW_RELIC_LICENSE_KEY"],
    oauth: false,
    docsUrl: "https://docs.newrelic.com",
    featured: false,
    available: true,
    agentTools: ["observe:log", "observe:metric"],
  },

  // --- Analytics ---
  {
    id: "posthog",
    name: "PostHog",
    description: "Understand your users — analytics, session replay, errors, flags, & more.",
    category: "analytics",
    tier: "native",
    envKeys: ["NEXT_PUBLIC_POSTHOG_KEY", "NEXT_PUBLIC_POSTHOG_HOST"],
    oauth: false,
    docsUrl: "https://posthog.com/docs",
    featured: true,
    available: true,
    agentTools: ["analytics:track", "analytics:identify", "flag:evaluate"],
  },
  {
    id: "statsig",
    name: "Statsig",
    description: "Performant Feature Flags, Experiments, Analytics, and Log Drains.",
    category: "analytics",
    tier: "native",
    envKeys: ["STATSIG_SERVER_API_KEY", "NEXT_PUBLIC_STATSIG_CLIENT_KEY"],
    oauth: false,
    docsUrl: "https://docs.statsig.com",
    featured: false,
    available: true,
    agentTools: ["flag:evaluate", "experiment:check"],
  },
  {
    id: "hypertune",
    name: "Hypertune",
    description: "Type-safe feature flags, experimentation, analytics, and app configuration.",
    category: "analytics",
    tier: "native",
    envKeys: ["HYPERTUNE_TOKEN"],
    oauth: false,
    docsUrl: "https://docs.hypertune.com",
    featured: false,
    available: true,
    agentTools: ["flag:evaluate", "config:get"],
  },
  {
    id: "growthbook",
    name: "GrowthBook",
    description: "Open source experimentation and feature flag management.",
    category: "analytics",
    tier: "native",
    envKeys: ["GROWTHBOOK_API_HOST", "GROWTHBOOK_CLIENT_KEY"],
    oauth: false,
    docsUrl: "https://docs.growthbook.io",
    featured: false,
    available: true,
    agentTools: ["flag:evaluate", "experiment:check"],
  },

  // --- Authentication ---
  {
    id: "clerk",
    name: "Clerk",
    description: "Drop-in authentication and subscription billing that scales with you.",
    category: "authentication",
    tier: "native",
    envKeys: ["NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", "CLERK_SECRET_KEY"],
    oauth: true,
    docsUrl: "https://clerk.com/docs",
    featured: true,
    available: true,
    agentTools: ["auth:verify_session", "auth:get_user"],
  },
  {
    id: "auth0",
    name: "Auth0",
    description: "Authentication for users or APIs.",
    category: "authentication",
    tier: "external",
    envKeys: ["AUTH0_DOMAIN", "AUTH0_CLIENT_ID", "AUTH0_CLIENT_SECRET"],
    oauth: true,
    docsUrl: "https://auth0.com/docs",
    featured: false,
    available: true,
    agentTools: ["auth:verify_token", "auth:get_user"],
  },
  {
    id: "descope",
    name: "Descope",
    description: "Drag-and-drop auth for your Vercel apps and remote MCP servers.",
    category: "authentication",
    tier: "agent",
    envKeys: ["DESCOPE_PROJECT_ID", "DESCOPE_MANAGEMENT_KEY"],
    oauth: true,
    docsUrl: "https://docs.descope.com",
    featured: false,
    available: true,
    agentTools: ["auth:flow", "auth:verify"],
  },

  // --- CMS ---
  {
    id: "sanity",
    name: "Sanity",
    description: "The content backend for shipping sites, apps and agents faster.",
    category: "cms",
    tier: "native",
    envKeys: ["SANITY_PROJECT_ID", "SANITY_DATASET", "SANITY_API_TOKEN"],
    oauth: false,
    docsUrl: "https://www.sanity.io/docs",
    featured: true,
    available: true,
    agentTools: ["cms:query", "cms:mutate", "cms:listen"],
  },
  {
    id: "contentful",
    name: "Contentful",
    description: "A modern content platform.",
    category: "cms",
    tier: "external",
    envKeys: ["CONTENTFUL_SPACE_ID", "CONTENTFUL_ACCESS_TOKEN"],
    oauth: false,
    docsUrl: "https://www.contentful.com/developers/docs",
    featured: false,
    available: true,
    agentTools: ["cms:query", "cms:publish"],
  },
  {
    id: "datocms",
    name: "DatoCMS",
    description: "User-friendly, performant Headless CMS.",
    category: "cms",
    tier: "external",
    envKeys: ["DATOCMS_API_TOKEN"],
    oauth: false,
    docsUrl: "https://www.datocms.com/docs",
    featured: false,
    available: true,
    agentTools: ["cms:query", "cms:publish"],
  },

  // --- Web Automation ---
  {
    id: "browserbase",
    name: "Browserbase",
    description: "Autonomously read, write, and perform tasks on the web with serverless browsers.",
    category: "web_automation",
    tier: "agent",
    envKeys: ["BROWSERBASE_API_KEY", "BROWSERBASE_PROJECT_ID"],
    oauth: false,
    docsUrl: "https://docs.browserbase.com",
    featured: true,
    available: true,
    agentTools: ["browser:navigate", "browser:click", "browser:extract", "browser:screenshot"],
  },
  {
    id: "kernel",
    name: "Kernel",
    description: "Crazy fast, open source infra for AI agents to access the internet.",
    category: "web_automation",
    tier: "agent",
    envKeys: ["KERNEL_API_KEY"],
    oauth: false,
    docsUrl: "https://kernel.sh/docs",
    featured: false,
    available: true,
    agentTools: ["browser:navigate", "browser:extract"],
  },

  // --- Support Agents ---
  {
    id: "assistloop",
    name: "AssistLoop",
    description: "Build an AI agent that handles support and escalates to humans when needed.",
    category: "support_agent",
    tier: "agent",
    envKeys: ["ASSISTLOOP_API_KEY"],
    oauth: false,
    docsUrl: "https://assistloop.com/docs",
    featured: false,
    available: true,
    agentTools: ["support:create_ticket", "support:escalate"],
  },
  {
    id: "chatbase",
    name: "Chatbase",
    description: "Build AI agents for improved customer service and satisfaction.",
    category: "support_agent",
    tier: "agent",
    envKeys: ["CHATBASE_API_KEY"],
    oauth: false,
    docsUrl: "https://chatbase.co/docs",
    featured: false,
    available: true,
    agentTools: ["support:chat", "support:train"],
  },

  // --- Code Review ---
  {
    id: "coderabbit",
    name: "CodeRabbit",
    description: "Cut Code Review Time & Bugs in Half. Instantly.",
    category: "code_review",
    tier: "agent",
    envKeys: ["CODERABBIT_API_KEY"],
    oauth: false,
    docsUrl: "https://coderabbit.ai/docs",
    featured: false,
    available: true,
    agentTools: ["code:review_pr"],
  },
  {
    id: "sourcery",
    name: "Sourcery",
    description: "Instant AI code reviews that cut bugs and security vulnerabilities.",
    category: "code_review",
    tier: "agent",
    envKeys: ["SOURCERY_TOKEN"],
    oauth: false,
    docsUrl: "https://docs.sourcery.ai",
    featured: false,
    available: true,
    agentTools: ["code:review", "code:refactor"],
  },
  {
    id: "corridor",
    name: "Corridor",
    description: "Instant security reviews and guardrails for AI coding.",
    category: "security",
    tier: "agent",
    envKeys: ["CORRIDOR_API_KEY"],
    oauth: false,
    docsUrl: "https://corridor.dev/docs",
    featured: false,
    available: true,
    agentTools: ["security:scan_code", "security:audit"],
  },

  // --- Searching ---
  {
    id: "parallel-web",
    name: "Parallel Web Systems",
    description: "The most accurate web search for AI — ranked results, snippets, and page content.",
    category: "searching",
    tier: "agent",
    envKeys: ["PARALLEL_WEB_API_KEY"],
    oauth: false,
    docsUrl: "https://parallelweb.com/docs",
    featured: false,
    available: true,
    agentTools: ["search:web", "search:extract"],
  },
  {
    id: "meilisearch",
    name: "Meilisearch Cloud",
    description: "Fast and relevant search out of the box.",
    category: "searching",
    tier: "external",
    envKeys: ["MEILISEARCH_HOST", "MEILISEARCH_API_KEY"],
    oauth: false,
    docsUrl: "https://docs.meilisearch.com",
    featured: false,
    available: true,
    agentTools: ["search:index", "search:query"],
  },

  // --- Messaging ---
  {
    id: "slack",
    name: "Slack",
    description: "Get Slack messages for comments, deployment status, and new projects.",
    category: "messaging",
    tier: "external",
    envKeys: ["SLACK_BOT_TOKEN", "SLACK_SIGNING_SECRET"],
    oauth: true,
    docsUrl: "https://api.slack.com/docs",
    featured: false,
    available: true,
    agentTools: ["msg:send_message", "msg:read_channel", "msg:search"],
  },
  {
    id: "resend",
    name: "Resend",
    description: "Email for developers.",
    category: "messaging",
    tier: "external",
    envKeys: ["RESEND_API_KEY"],
    oauth: false,
    docsUrl: "https://resend.com/docs",
    featured: false,
    available: true,
    agentTools: ["email:send", "email:batch"],
  },
  {
    id: "knock",
    name: "Knock",
    description: "Messaging API for developers.",
    category: "messaging",
    tier: "external",
    envKeys: ["KNOCK_API_KEY", "KNOCK_SIGNING_KEY"],
    oauth: false,
    docsUrl: "https://docs.knock.app",
    featured: false,
    available: true,
    agentTools: ["notify:send", "notify:workflow"],
  },
  {
    id: "novu",
    name: "Novu",
    description: "The OSS notification infrastructure.",
    category: "messaging",
    tier: "external",
    envKeys: ["NOVU_API_KEY"],
    oauth: false,
    docsUrl: "https://docs.novu.co",
    featured: false,
    available: true,
    agentTools: ["notify:trigger"],
  },

  // --- Payments ---
  {
    id: "stripe",
    name: "Stripe",
    description: "A fully integrated suite of financial and payments products.",
    category: "payments",
    tier: "native",
    envKeys: ["STRIPE_SECRET_KEY", "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY", "STRIPE_WEBHOOK_SECRET"],
    oauth: false,
    docsUrl: "https://stripe.com/docs",
    featured: true,
    available: true,
    agentTools: ["pay:create_checkout", "pay:list_invoices", "pay:create_subscription"],
  },

  // --- Video ---
  {
    id: "mux",
    name: "Mux",
    description: "Add video to your app in minutes.",
    category: "video",
    tier: "native",
    envKeys: ["MUX_TOKEN_ID", "MUX_TOKEN_SECRET"],
    oauth: false,
    docsUrl: "https://docs.mux.com",
    featured: false,
    available: true,
    agentTools: ["video:upload", "video:get_playback", "video:analytics"],
  },

  // --- DevTools ---
  {
    id: "inngest",
    name: "Inngest",
    description: "Run AI workflows and agents with confidence.",
    category: "devtools",
    tier: "native",
    envKeys: ["INNGEST_EVENT_KEY", "INNGEST_SIGNING_KEY"],
    oauth: false,
    docsUrl: "https://www.inngest.com/docs",
    featured: true,
    available: true,
    agentTools: ["workflow:trigger", "workflow:schedule", "workflow:step"],
  },
  {
    id: "liveblocks",
    name: "Liveblocks",
    description: "Real-time collaboration infrastructure for developers.",
    category: "devtools",
    tier: "external",
    envKeys: ["LIVEBLOCKS_SECRET_KEY"],
    oauth: false,
    docsUrl: "https://liveblocks.io/docs",
    featured: false,
    available: true,
    agentTools: ["collab:presence", "collab:storage"],
  },

  // --- Testing ---
  {
    id: "autonoma",
    name: "Autonoma AI",
    description: "AI-based web platform to create and run end-to-end tests.",
    category: "testing",
    tier: "agent",
    envKeys: ["AUTONOMA_API_KEY"],
    oauth: false,
    docsUrl: "https://autonoma.ai/docs",
    featured: false,
    available: true,
    agentTools: ["test:create", "test:run", "test:report"],
  },

  // --- Security ---
  {
    id: "arcjet",
    name: "Arcjet",
    description: "Security as code.",
    category: "security",
    tier: "external",
    envKeys: ["ARCJET_KEY"],
    oauth: false,
    docsUrl: "https://docs.arcjet.com",
    featured: false,
    available: true,
    agentTools: ["security:rate_limit", "security:bot_detect", "security:shield"],
  },

  // --- Logging ---
  {
    id: "axiom",
    name: "Axiom",
    description: "Logs, functions, and Web Vitals insights.",
    category: "logging",
    tier: "external",
    envKeys: ["AXIOM_TOKEN", "AXIOM_DATASET"],
    oauth: false,
    docsUrl: "https://axiom.co/docs",
    featured: false,
    available: true,
    agentTools: ["log:ingest", "log:query"],
  },

  // --- Commerce ---
  {
    id: "shopify",
    name: "Shopify",
    description: "Headless, composable storefronts.",
    category: "commerce",
    tier: "external",
    envKeys: ["SHOPIFY_STORE_DOMAIN", "SHOPIFY_STOREFRONT_ACCESS_TOKEN"],
    oauth: true,
    docsUrl: "https://shopify.dev/docs",
    featured: false,
    available: true,
    agentTools: ["commerce:list_products", "commerce:create_checkout"],
  },

  // --- Coming Soon ---
  {
    id: "browser-use",
    name: "Browser Use",
    description: "Coming soon — advanced browser automation for AI agents.",
    category: "web_automation",
    tier: "agent",
    envKeys: [],
    oauth: false,
    docsUrl: "",
    featured: false,
    available: false,
    agentTools: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GOVERNMENT-IN-THE-LOOP INTEGRATIONS
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "sam-gov",
    name: "SAM.gov",
    description: "Federal contracts, grants, and entity registration via the System for Award Management.",
    category: "government",
    tier: "external",
    envKeys: ["SAM_GOV_API_KEY"],
    oauth: false,
    docsUrl: "https://open.gsa.gov/api/entity-api/",
    featured: true,
    available: true,
    agentTools: ["sam:search_entities", "sam:check_exclusions", "sam:get_opportunities", "sam:verify_registration"],
  },
  {
    id: "edgar-sec",
    name: "SEC EDGAR",
    description: "Securities filings, company data, and financial disclosures from the SEC.",
    category: "government",
    tier: "external",
    envKeys: ["SEC_EDGAR_USER_AGENT"],
    oauth: false,
    docsUrl: "https://www.sec.gov/edgar/searchedgar/efulltext.htm",
    featured: true,
    available: true,
    agentTools: ["edgar:search_filings", "edgar:get_company", "edgar:get_filing", "edgar:list_recent"],
  },
  {
    id: "pacer",
    name: "PACER",
    description: "Federal court records — case filings, dockets, and judicial opinions.",
    category: "government",
    tier: "external",
    envKeys: ["PACER_USERNAME", "PACER_PASSWORD"],
    oauth: false,
    docsUrl: "https://pacer.uscourts.gov/",
    featured: false,
    available: true,
    agentTools: ["pacer:search_cases", "pacer:get_docket", "pacer:get_document"],
  },
  {
    id: "regulations-gov",
    name: "Regulations.gov",
    description: "Federal rulemaking — proposed rules, comment periods, and regulatory dockets.",
    category: "government",
    tier: "external",
    envKeys: ["REGULATIONS_GOV_API_KEY"],
    oauth: false,
    docsUrl: "https://open.gsa.gov/api/regulationsgov/",
    featured: true,
    available: true,
    agentTools: ["regulations:search_dockets", "regulations:get_document", "regulations:list_comments", "regulations:submit_comment"],
  },
  {
    id: "ofac-screening",
    name: "OFAC Sanctions Screening",
    description: "Screen entities against the Treasury OFAC SDN and Consolidated Sanctions lists.",
    category: "government",
    tier: "external",
    envKeys: [],
    oauth: false,
    docsUrl: "https://ofac.treasury.gov/specially-designated-nationals-list-sdn-list",
    featured: true,
    available: true,
    agentTools: ["ofac:screen_entity", "ofac:search_sdn", "ofac:check_country"],
  },
  {
    id: "uspto",
    name: "USPTO",
    description: "Patent and trademark search, application tracking, and IP portfolio management.",
    category: "government",
    tier: "external",
    envKeys: ["USPTO_API_KEY"],
    oauth: false,
    docsUrl: "https://developer.uspto.gov/",
    featured: false,
    available: true,
    agentTools: ["uspto:search_patents", "uspto:search_trademarks", "uspto:get_application_status"],
  },
  {
    id: "foia-gov",
    name: "FOIA.gov",
    description: "Freedom of Information Act request submission and tracking across federal agencies.",
    category: "government",
    tier: "external",
    envKeys: [],
    oauth: false,
    docsUrl: "https://www.foia.gov/developer/",
    featured: false,
    available: true,
    agentTools: ["foia:submit_request", "foia:check_status", "foia:list_agencies"],
  },
  {
    id: "congress-gov",
    name: "Congress.gov",
    description: "Legislative data — bills, votes, members, and committee actions via the Library of Congress API.",
    category: "government",
    tier: "external",
    envKeys: ["CONGRESS_GOV_API_KEY"],
    oauth: false,
    docsUrl: "https://api.congress.gov/",
    featured: false,
    available: true,
    agentTools: ["congress:search_bills", "congress:get_member", "congress:get_votes", "congress:track_legislation"],
  },
  {
    id: "federal-register",
    name: "Federal Register",
    description: "Daily journal of the US Government — executive orders, proposed rules, notices.",
    category: "government",
    tier: "external",
    envKeys: [],
    oauth: false,
    docsUrl: "https://www.federalregister.gov/developers/documentation/api/v1",
    featured: false,
    available: true,
    agentTools: ["fedreg:search_documents", "fedreg:get_document", "fedreg:list_agencies"],
  },
  {
    id: "bis-export-control",
    name: "BIS Export Control",
    description: "Bureau of Industry and Security — entity list screening and export classification.",
    category: "government",
    tier: "external",
    envKeys: [],
    oauth: false,
    docsUrl: "https://www.bis.doc.gov/",
    featured: false,
    available: true,
    agentTools: ["bis:screen_entity", "bis:check_eccn", "bis:verify_license"],
  },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Get all integrations for a given category */
export function getIntegrationsByCategory(category: IntegrationCategory): IntegrationEntry[] {
  return INTEGRATION_CATALOG.filter((i) => i.category === category)
}

/** Get all integrations for a given tier */
export function getIntegrationsByTier(tier: IntegrationTier): IntegrationEntry[] {
  return INTEGRATION_CATALOG.filter((i) => i.tier === tier)
}

/** Get featured integrations */
export function getFeaturedIntegrations(): IntegrationEntry[] {
  return INTEGRATION_CATALOG.filter((i) => i.featured)
}

/** Get available integrations (excludes coming soon) */
export function getAvailableIntegrations(): IntegrationEntry[] {
  return INTEGRATION_CATALOG.filter((i) => i.available)
}

/** Check if an integration has its env vars configured */
export function isIntegrationConfigured(id: string, env: Record<string, string | undefined>): boolean {
  const entry = INTEGRATION_CATALOG.find((i) => i.id === id)
  if (!entry || entry.envKeys.length === 0) return false
  return entry.envKeys.every((key) => !!env[key])
}

/** Get all unique categories in the catalog */
export function getAllCategories(): IntegrationCategory[] {
  return [...new Set(INTEGRATION_CATALOG.map((i) => i.category))]
}

/** Category display labels */
export const CATEGORY_LABELS: Record<IntegrationCategory, string> = {
  ai: "AI",
  storage: "Storage",
  observability: "Observability",
  analytics: "Analytics",
  authentication: "Authentication",
  cms: "CMS",
  commerce: "Commerce",
  messaging: "Messaging",
  monitoring: "Monitoring",
  searching: "Searching",
  security: "Security",
  web_automation: "Web Automation",
  support_agent: "Support Agent",
  code_review: "Code Review",
  testing: "Testing",
  devtools: "DevTools",
  logging: "Logging",
  video: "Video",
  payments: "Payments",
  government: "Government",
}
